name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.19.x, 1.20.x]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Go dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: |
        export PATH=~/go/bin:$PATH
        go install -v github.com/markbates/pkger/cmd/pkger@v0.17.1
        make build

    - name: Unit tests
      run: go test ./...
